# Generated by Django 5.2.8 on 2026-06-27 17:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_authorprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="language_code",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.CreateModel(
            name="PostTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether this record is active or not.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time of the last update to the record.",
                        verbose_name="Updated At",
                    ),
                ),
                ("language_code", models.CharField(db_index=True, max_length=10)),
                ("slug", models.SlugField(allow_unicode=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("excerpt", models.TextField()),
                ("content", django_ckeditor_5.fields.CKEditor5Field(config_name="default")),
                ("reading_time_sec", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language_code", "slug"],
                        name="posts_postt_languag_d94e77_idx",
                    )
                ],
                "unique_together": {
                    ("post", "language_code"),
                    ("slug", "language_code"),
                },
            },
        ),
    ]
