# Generated by Django 5.2.8 on 2026-07-11 20:36

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_old_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether this record is active or not.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time of the last update to the record.",
                        verbose_name="Updated At",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PodcastCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether this record is active or not.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time of the last update to the record.",
                        verbose_name="Updated At",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True, null=True, upload_to="podcasts/categories/icons/"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Podcast Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to="categories/icons/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="related_posts",
            field=models.ManyToManyField(blank=True, to="posts.post"),
        ),
        migrations.AddField(
            model_name="posttranslation",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether this record is active or not.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time of the last update to the record.",
                        verbose_name="Updated At",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
                ("episode_number", models.PositiveIntegerField()),
                ("cover_image", models.ImageField(upload_to="podcasts/covers/")),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="podcasts/audio/"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("audio", "Audio"), ("video", "Video")],
                        default="audio",
                        max_length=10,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True, null=True, upload_to="podcasts/video/"
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("description", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("published_date", models.DateTimeField()),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "related_podcasts",
                    models.ManyToManyField(blank=True, to="posts.podcast"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcasts",
                        to="posts.podcastcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date", "-id"],
            },
        ),
    ]
