# Generated by Django 5.2.8 on 2026-07-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0006_alter_articlemedia_options_alter_articlemedia_media"),
        ("posts", "0007_rename_post_to_article"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="articletranslation",
            new_name="posts_artic_languag_c5bea0_idx",
            old_name="posts_postt_languag_d94e77_idx",
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_covers",
                to="medias.media",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_og_images",
                to="medias.media",
            ),
        ),
    ]
