# Generated by Django 5.2.8 on 2026-07-28 19:52

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "posts",
            "0008_rename_posts_postt_languag_d94e77_idx_posts_artic_languag_c5bea0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articletranslation",
            name="content_blocks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
