# Generated by Django 5.2.8 on 2026-08-16 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0007_media_checksum_algorithm_media_content_hash_and_more"),
        ("posts", "0009_articletranslation_content_blocks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category_icons",
                to="medias.media",
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_items",
                to="medias.media",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="audio_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_audios",
                to="medias.media",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_covers",
                to="medias.media",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="video_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_videos",
                to="medias.media",
            ),
        ),
        migrations.AlterField(
            model_name="podcastcategory",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_category_icons",
                to="medias.media",
            ),
        ),
    ]
