# Generated by Django 5.2.8 on 2026-01-02 08:42

import common.fields
import common.utils.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[(1, "Level 1"), (2, "Level 2"), (3, "Level 3")],
                        default=1,
                    ),
                ),
                (
                    "id_card_image",
                    common.fields.OptimizedImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.files.get_sanitized_upload_path,
                    ),
                ),
                (
                    "selfie_image",
                    common.fields.OptimizedImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.files.get_sanitized_upload_path,
                    ),
                ),
                (
                    "video",
                    common.fields.OptimizedVideoField(
                        blank=True, null=True, upload_to="verification_videos/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
