# Generated by Django 5.2.8 on 2026-01-02 08:42

import common.fields
import common.utils.files
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ongoing", "Ongoing"),
                            ("pending_confirmation", "Pending Confirmation"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("round", models.IntegerField()),
                (
                    "result_proof",
                    common.fields.OptimizedImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.files.get_sanitized_upload_path,
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_disputed", models.BooleanField(default=False)),
                ("dispute_reason", models.TextField(blank=True)),
                ("room_id", models.CharField(blank=True, max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("checked_in", "Checked-in"),
                            ("eliminated", "Eliminated"),
                        ],
                        db_index=True,
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "prize",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    common.fields.OptimizedImageField(
                        upload_to=common.utils.files.get_sanitized_upload_path
                    ),
                ),
                ("required_score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "evidence",
                    common.fields.OptimizedImageField(
                        blank=True,
                        null=True,
                        upload_to=common.utils.files.get_sanitized_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("team_deathmatch", "Team Deathmatch"),
                            ("battle_royale", "Battle Royale"),
                        ],
                        default="team_deathmatch",
                        max_length=20,
                    ),
                ),
                ("max_participants", models.PositiveIntegerField(default=100)),
                (
                    "winner_slots",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum number of winners eligible for rewards. Set to 1 for champion-only payouts.",
                    ),
                ),
                ("team_size", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "registration_start_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("registration_end_date", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                ("is_free", models.BooleanField(default=True)),
                ("is_token_based", models.BooleanField(default=False)),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total prize pool in Rial.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("rules", models.TextField(blank=True)),
                ("countdown_start_time", models.DateTimeField(blank=True, null=True)),
                ("required_verification_level", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("rgb_code", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image",
                    common.fields.OptimizedImageField(
                        upload_to=common.utils.files.get_sanitized_upload_path
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WinnerSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    common.fields.OptimizedImageField(
                        blank=True, null=True, upload_to="winner_submissions/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GameImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("hero_banner", "Hero Banner"),
                            ("cta_banner", "CTA Banner"),
                            ("game_image", "Game Image"),
                            ("thumbnail", "Thumbnail"),
                            ("icon", "Icon"),
                            ("slider", "Slider"),
                            ("illustration", "Illustration"),
                            ("promotional_banner", "Promotional Banner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    common.fields.OptimizedImageField(
                        upload_to=common.utils.files.get_sanitized_upload_path
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tournaments.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="tournaments.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Manager",
                "verbose_name_plural": "Game Managers",
            },
        ),
    ]
