# Generated by Django 5.2.8 on 2026-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("revenue_report", "Revenue Report"),
                            ("players_report", "Players Report"),
                            ("tournament_report", "Tournament Report"),
                            ("finance_report", "Finance Report"),
                            ("marketing_roi_report", "Marketing ROI Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                ("filters", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Generated Report",
                "verbose_name_plural": "Generated Reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type"], name="reporting_r_report__5d34ee_idx"
                    )
                ],
            },
        ),
    ]
