# Generated by Django 5.2.8 on 2026-07-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0005_rename_postmedia_to_articlemedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlemedia",
            options={
                "verbose_name": "Article Media",
                "verbose_name_plural": "Article Media",
            },
        ),
        migrations.AlterField(
            model_name="articlemedia",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_attachments",
                to="medias.media",
            ),
        ),
    ]
