# Generated by Django 5.2.8 on 2026-07-28 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0006_alter_articlemedia_options_alter_articlemedia_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="checksum_algorithm",
            field=models.CharField(default="SHA256", max_length=10),
        ),
        migrations.AddField(
            model_name="media",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="media",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Ready", "Ready"),
                    ("Rejected", "Rejected"),
                    ("Quarantined", "Quarantined"),
                ],
                default="Ready",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MediaVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Specifies whether this record is active or not.",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the record was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The time of the last update to the record.",
                        verbose_name="Updated At",
                    ),
                ),
                ("variant_name", models.CharField(max_length=50)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("format", models.CharField(max_length=20)),
                ("storage_key", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="medias.media",
                    ),
                ),
            ],
            options={
                "ordering": ["variant_name"],
            },
        ),
    ]
