# Generated by Django 5.2.8 on 2026-01-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rewards", "0001_initial"),
        ("tournaments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="spin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="wheel",
            name="required_rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournaments.rank"
            ),
        ),
        migrations.AddField(
            model_name="spin",
            name="wheel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rewards.wheel"
            ),
        ),
        migrations.AddField(
            model_name="prize",
            name="wheel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prizes",
                to="rewards.wheel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spin",
            unique_together={("user", "wheel")},
        ),
    ]
