# Generated by Django 5.2.8 on 2026-01-02 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("entry_fee", "Entry Fee"),
                            ("prize", "Prize"),
                            ("token_spent", "Token Spent"),
                            ("token_earned", "Token Earned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        help_text="Zibal trackId",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique order ID for the transaction",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "ref_number",
                    models.CharField(
                        blank=True,
                        help_text="Zibal reference number after successful payment",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "is_refunded",
                    models.BooleanField(
                        default=False, help_text="آیا این تراکنش استرداد شده است؟"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "refund_id",
                    models.CharField(
                        help_text="شناسه استرداد از زیبال", max_length=255, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="wallet.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "withdrawable_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "token_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, help_text="شماره کارت", max_length=16, null=True
                    ),
                ),
                (
                    "sheba_number",
                    models.CharField(
                        blank=True, help_text="شماره شبا", max_length=26, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="wallet.wallet",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار بررسی"),
                            ("approved", "تایید شده"),
                            ("rejected", "رد شده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
