"""
Django settings for tournament_project project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import locale
import os
import sys
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv
from kombu import Exchange, Queue

# if sys.platform.startswith("win32"):
#     locale.setlocale(locale.LC_ALL, "Persian_Iran.UTF-8")
# else:
#     locale.setlocale(locale.LC_ALL, "fa_IR.UTF-8")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

IS_MANAGEMENT_COMMAND = 'manage.py' in sys.argv[0]

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dummy-key-for-testing")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "t")

# Site configuration
DOMAIN = os.environ.get("DOMAIN", "localhost")
SITE_NAME = os.environ.get("SITE_NAME", "Tournament Platform")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "").strip()

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", f"localhost,127.0.0.1,{DOMAIN}").split(",")


# Application definition

INSTALLED_APPS = [
    "django_ckeditor_5",
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "rest_framework",
    "channels",
    "django_filters",
    "phonenumber_field",
    "drf_spectacular",  # Required for drf-spectacular
    "users",
    "common",
    "teams",
    "tournaments",
    "wallet",
    "corsheaders",
    "axes",
    "chat",
    "notifications",
    "django_celery_results",
    "djoser",
    "support",
    "sslserver",
    "verification",
    "rewards",
    "reporting",
    "guardian",
    "simple_history",
    "import_export",
    "silk",
    "django_select2",
    "jalali_date",
    "tempus_dominus",
    "formtools",
    "management_dashboard",
    "atomgamebot",
    "blog",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]

if "test" not in sys.argv and "pytest" not in sys.modules:
    AUTHENTICATION_BACKENDS.insert(0, "axes.backends.AxesStandaloneBackend")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "tournament_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tournament_project.wsgi.application"
ASGI_APPLICATION = "tournament_project.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

is_testing_db = "test" in sys.argv or "pytest" in sys.modules

if is_testing_db:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASE_URL = os.environ.get("DATABASE_URL")
    if DATABASE_URL:
        DATABASES = {"default": dj_database_url.config(default=DATABASE_URL)}
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i1n/

LANGUAGE_CODE = "fa"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

MEDIA_URL = os.environ.get("MEDIA_URL", "/media/")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
PRIVATE_MEDIA_ROOT = os.path.join(BASE_DIR, "private_media")

# Custom Storage Settings
STORAGE_BACKEND = os.environ.get("STORAGE_BACKEND", "local")

if STORAGE_BACKEND == "s3":
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME")
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_LOCATION = "media"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/"
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379")

if "test" in sys.argv:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "json": {
            "class": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(module)s %(lineno)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file_info": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/app.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "verbose",
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/error.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "json",
        },
        "smtp_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/smtp.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 2,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file_info", "file_error"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["mail_admins", "file_error"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.core.mail": {
            "handlers": ["smtp_file"],
            "level": "INFO",
            "propagate": True,
        },
        "root": {
            "handlers": ["console", "file_info", "file_error"],
            "level": "INFO",
        },
    },
}

# Use console logging in development and file/email logging in production
if DEBUG or "test" in sys.argv or "pytest" in sys.modules:
    LOGGING["loggers"]["django"]["handlers"] = ["console"]
    LOGGING["loggers"]["root"]["handlers"] = ["console"]
else:
    LOGGING["loggers"]["django"]["handlers"] = ["file_info", "file_error"]
    LOGGING["loggers"]["django"]["propagate"] = False
    LOGGING["loggers"]["root"]["handlers"] = ["file_info", "file_error", "mail_admins"]


UNFOLD = {
    "SITE_HEADER": "Tournament Platform",
    "SITE_TITLE": "Tournament Platform Admin",
    "SITE_URL": "/",
    "THEME": "dark",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
    "DASHBOARD_CALLBACK": "reporting.views.dashboard_callback",
}

# Django REST Framework Settings
REST_FRAMEWORK = {
    # This line is required for drf-spectacular
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # This line is for using JWT Authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Default throttle classes are removed to enforce endpoint-specific throttling.
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {
        'very_strict': '1/minute',
        'strict': '10/minute',
        'medium': '100/minute',
        'relaxed': '500/hour',
        # Legacy throttles are kept for reference but should not be used directly.
        "anon": os.environ.get("API_THROTTLE_RATE_ANON", "1000/day"),
        "user": os.environ.get("API_THROTTLE_RATE_USER", "10000/day"),
    },
    'EXCEPTION_HANDLER': 'blog.exceptions.custom_exception_handler',
}

# Disable throttling during tests by setting high throttle rates.
if "test" in sys.argv or "pytest" in sys.modules:
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        'very_strict': '10000/s',
        'strict': '10000/s',
        'medium': '10000/s',
        'relaxed': '10000/s',
        "anon": '10000/s',
        "user": '10000/s',
    }

SPECTACULAR_SETTINGS = {
    "TITLE": f"{SITE_NAME} API",
    "DESCRIPTION": "API for managing tournaments, users, wallets, and more.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # Optional: hides the schema endpoint from the UI
    "SCHEMA_PATH_PREFIX": r"/api",
    "ENUM_NAME_OVERRIDES": {
        "StatusD53Enum": "tournaments.models.Game.Status",
        "StatusE7cEnum": "tournaments.models.Match.Status",
        "Status224Enum": "tournaments.models.Participant.Status",
        "TypeEnum": "tournaments.models.Tournament.TournamentType",
    },
}

DJOSER = {
    "PASSWORD_RESET_CONFIRM_URL": f"{FRONTEND_URL}/#/password/reset/confirm/{{uid}}/{{token}}",
    "USERNAME_RESET_CONFIRM_URL": f"{FRONTEND_URL}/#/username/reset/confirm/{{uid}}/{{token}}",
    "ACTIVATION_URL": f"{FRONTEND_URL}/#/activate/{{uid}}/{{token}}",
    "SEND_ACTIVATION_EMAIL": True,
    "USER_CREATE_PASSWORD_RETYPE": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": True,
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "SET_USERNAME_RETYPE": True,
    "SET_PASSWORD_RETYPE": True,
    "SERIALIZERS": {},
    "SITE_NAME": SITE_NAME,
}


FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# In production (when DEBUG is False), redirect all HTTP requests to HTTPS.
# We disable this during tests as the test client makes plain HTTP requests.
is_testing = "test" in sys.argv or 'pytest' in sys.modules

SECURE_SSL_REDIRECT = not DEBUG and not is_testing
# In production, use secure cookies.
SESSION_COOKIE_SECURE = not DEBUG and not is_testing
CSRF_COOKIE_SECURE = not DEBUG and not is_testing

if not DEBUG and not is_testing:
    MIDDLEWARE.insert(2, "silk.middleware.SilkyMiddleware")

CORS_ALLOWED_ORIGINS = [
    origin for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",") if origin
]

if DEBUG:
    CORS_ALLOWED_ORIGINS.extend(
        [
            "http://127.0.0.1:5501",
            "http://localhost:5501",
        ]
    )

CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False").lower() in ("true", "1", "t")
ZIBAL_PAYMENT_SUCCESS_URL = "https://atom-game.ir/payment/success.html"
ZIBAL_PAYMENT_FAILED_URL = "https://atom-game.ir/payment/failed.html"

MINIMUM_WITHDRAWAL_AMOUNT = int(
    os.environ.get("MINIMUM_WITHDRAWAL_AMOUNT", "1000000")
)

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1
AXES_RESET_ON_SUCCESS = True
AXES_NEVER_LOCKOUT_CALLABLE = "users.auth_utils.should_never_lockout_staff"

ZIBAL_MERCHANT_ID = os.environ.get("ZIBAL_MERCHANT_ID", "zibal")

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Tehran"
CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_QUEUES = (
    Queue("high_priority", Exchange("high_priority"), routing_key="high_priority"),
    Queue("default", Exchange("default"), routing_key="default"),
    Queue("low_priority", Exchange("low_priority"), routing_key="low_priority"),
)
CELERY_TASK_ROUTES = {
    "tournaments.tasks.run_seed_data_task": {
        "queue": "low_priority",
        "routing_key": "low_priority",
    }
}
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(
    os.environ.get("CELERY_WORKER_MAX_TASKS_PER_CHILD", "100")
)
CELERY_TASK_SOFT_TIME_LIMIT = int(os.environ.get("CELERY_TASK_SOFT_TIME_LIMIT", "900"))
CELERY_TASK_TIME_LIMIT = int(os.environ.get("CELERY_TASK_TIME_LIMIT", "960"))
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": int(os.environ.get("CELERY_VISIBILITY_TIMEOUT", "1200"))
}
CELERY_RESULT_EXPIRES = timedelta(
    hours=int(os.environ.get("CELERY_RESULT_EXPIRES_HOURS", "24"))
)

CELERY_BEAT_SCHEDULE = {
    'publish-scheduled-posts': {
        'task': 'blog.tasks.publish_scheduled_posts',
        'schedule': timedelta(minutes=1),
    },
}

if "test" in sys.argv or "pytest" in sys.modules:
    CELERY_TASK_ALWAYS_EAGER = True
    # Disable guardian's anonymous user during tests to prevent test failures
    ANONYMOUS_USER_NAME = None

# SMS.ir Configuration
SMSIR_API_KEY = os.environ.get("SMSIR_API_KEY")
SMSIR_LINE_NUMBER = os.environ.get("SMSIR_LINE_NUMBER")

# Email Configuration
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("true", "1", "t")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")

CSRF_TRUSTED_ORIGINS = [
    "https://atom-game.ir",
    "https://www.atom-game.ir",
]



CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",  # DB 1 for cache, 0 for channels/celery
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

if "test" in sys.argv or "pytest" in sys.modules:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

CKEDITOR_5_UPLOAD_PATH = "uploads/"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "link",
            "bulletedList",
            "numberedList",
            "outdent",
            "indent",
            "blockQuote",
            "insertTable",
            "imageUpload",
            "mediaEmbed",
            "undo",
            "redo",
        ],
        "uploadUrl": "/blog/upload/",
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "imageStyle:inline",
                "imageStyle:block",
                "imageStyle:side",
            ]
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
            ]
        },
        "mediaEmbed": {"previewsInData": True},
        "link": {"addTargetToExternalLinks": True},
    }
}

JALALI_DATE_DEFAULTS = {
   'LIST_DISPLAY_AUTO_CONVERT': True
}
