# Generated by Django 5.2.5 on 2025-11-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="AtomGameBot", max_length=100, unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Activate the bot to start its tasks. Deactivate to stop.",
                    ),
                ),
            ],
            options={
                "verbose_name": "AtomGameBot Settings",
                "verbose_name_plural": "AtomGameBot Settings",
            },
        ),
    ]
