# Generated by Django 5.2.8 on 2026-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("report_new", "گزارش جدید"),
                            ("report_status_change", "تغییر وضعیت گزارش"),
                            ("winner_submission_required", "نیاز به ارسال نتیجه"),
                            (
                                "winner_submission_status_change",
                                "تغییر وضعیت ارسال نتیجه",
                            ),
                            ("verification_status_change", "تغییر وضعیت احراز هویت"),
                        ],
                        default="report_status_change",
                        max_length=50,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
